### PR TITLE
fix(back): add auth service interface & clerk implem

### LINKED ISSUE #377: refactor(back): add an auth service agnostic from provider
for now we use functions as GetFromClerkID directly in the ZenaoServer object
we want a new interface auth provider agnostic that implements these functions:

an implementation using Clerk should be implemented in a pkg called ``czauth -> clerk zenao auth``  based on the naming of ``gzdb -> gorm zenao db``

```go
type Auth interface {
	GetUser              func(ctx context.Context) *zeni.AuthUser
	GetUsersFromIDs func(ctx context.Context, ids []string) ([]*zeni.AuthUser, error)
	CreateUser           func(ctx context.Context, email string) (*zeni.AuthUser, error)
}
```

### PR DESCRIPTION
**Pull request by MikaelVallenet**
fix #377
depends on #373 

-----------------------------

This PR refactor the clerk auth functions to build an auth interface to be auth provider agnostic
It also includes a Clerk implementation of this interface called ``czauth``

Here is the list:
- New Interface ``Auth``
```go
type Auth interface {
	GetUser(ctx context.Context) *AuthUser
	GetUsersFromIDs(ctx context.Context, ids []string) ([]*AuthUser, error)
	CreateUser(ctx context.Context, email string) (*AuthUser, error)

	WithAuth() func(http.Handler) http.Handler
}
```
- Remove the functions  above from ``ZenaoServer`` to be replaced by ``zeni.Auth`` obj
- Move all the functions previously defined in ``main.go`` into ``czauth/auth.go``

### CODE REVIEW

**Review by n0izn0iz — APPROVED** [review]
Cool :)

File: backend/czauth/auth.go [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+		if len(clerkUser.EmailAddresses) != 0 {
+			email = clerkUser.EmailAddresses[0].EmailAddress
+		}
+		users[i] = &zeni.AuthUser{ID: clerkUser.ID, Banned: clerkUser.Banned, Email: email}
+	}
+	return users, nil
+}
+
+// CreateUser implements zeni.Auth.
+func (c *clerkZenaoAuth) CreateUser(ctx context.Context, email string) (*zeni.AuthUser, error) {
```
Comment (n0izn0iz) [inline backend/czauth/auth.go:58]:
```suggestion
func (c *clerkZenaoAuth) EnsureUserExists(ctx context.Context, email string) (*zeni.AuthUser, error) {
```

Comment (MikaelVallenet) [reply backend/czauth/auth.go]: fix: [9919f77](https://github.com/samouraiworld/zenao/pull/378/commits/9919f77898e4f98fe011350816be270f7e91711e)
& [a2e1852](https://github.com/samouraiworld/zenao/pull/378/commits/a2e1852561b12e8abcbd85120c89c2e3eb4977de)
