### PR TITLE
feat(front): new form field image & fix date picker bad initial state on edit event

### LINKED ISSUE #202: improve image form field
- I think we should have some feedback while the image is uploading (like a loader superimposed or a skeleton)
- The image preview/view should have a fixed size (especially for pfp, should be a square)
- The whole image should be clickable and not just a little button in the corner, see github for example, the whole image is clickable and it shows a popover on hover:
Screenshot 2025-02-22 at 17 12 50

### PR DESCRIPTION
**Pull request by pr0m3th3usEx**
Fix #202 
- [X] Bugfix when organizer edits its his event, endDate picker is not well populated

### CODE REVIEW

File: components/form/components/form-field-date-picker.tsx [hunk 1]
```diff
@@ -218,8 +216,10 @@ export function FormFieldDatePicker<T extends FieldValues>(
                   onValueChange={(e) => {
                     setTime(e);
                     if (field.value) {
+                      console.log(field.value);
```
Comment (n0izn0iz) [inline components/form/components/form-field-date-picker.tsx:219]: pls remove console logs

**Review by n0izn0iz — CHANGES_REQUESTED** [review]
