### PR TITLE
fix: ignore email error & avoid rollback db after chain success

### LINKED ISSUE #299: bug: event created on chain but record not found in database
this event is created on chain: https://zenao-gno.fly.dev/r/zenao/events/e13 but cannot interact with it since database says record not found
i think it's because if a sending mail fail, we rollback the database and return error but we do it after creating the event on chain and this cannot be rollback

2 solutions:
-> we do the mail sending before chain logic, however if chain fail db will be reset but the mail will be sent anyway
-> we ignore the mail error, so maybe we can have an event created without receiving mail (i think it's the best case)

### PR DESCRIPTION
**Pull request by MikaelVallenet**
fix #299

### CODE REVIEW

File: backend/participate.go [hunk 1]
```diff
@@ -41,14 +41,17 @@ func (s *ZenaoServer) Participate(ctx context.Context, req *connect.Request[zena
...
+
 	if err := s.DB.Tx(func(db zeni.DB) error {
 		// XXX: can't create event with price for now but later we need to check that the event is free
 
 		if err := db.Participate(req.Msg.EventId, userID); err != nil {
 			return err
 		}
 
-		evt, err := db.GetEvent(req.Msg.EventId)
+		var err error
```
Comment (MikaelVallenet) [inline backend/participate.go:53]: remove this

Comment (MikaelVallenet) [inline backend/participate.go:53]: remove this
