### PR TITLE
fix(front): gatekeeper-event-dialog: fix copy/paste not enabling + button

### LINKED ISSUE #836: bug: pasting a mail in gatekeeper input does not enable `+` sign
Image

it seems also that the address is not saved when clicking on done when the plus sign is not enabled

### PR DESCRIPTION
**Pull request by pr0m3th3usEx**
Fix #836

### CODE REVIEW

File: components/dialogs/gatekeeper-management-dialog.tsx [hunk 1]
```diff
@@ -69,8 +70,10 @@ function GatekeeperManagementForm({
     internalForm.reset();
   };
 
-  const isAddButtonEnabled =
-    internalForm.formState.isValid && internalForm.formState.isDirty;
+  const isAddButtonEnabled = useMemo(
```
Comment (MikaelVallenet) [inline components/dialogs/gatekeeper-management-dialog.tsx]: why useMemo here ?

Comment (pr0m3th3usEx) [reply components/dialogs/gatekeeper-management-dialog.tsx]: We want to make sure the reevaluation of `isAddButtonEnabled` is triggered when child properties `isValid` && `isDirty` are updated because `formState` is not reactive itself.

Comment (MikaelVallenet) [reply components/dialogs/gatekeeper-management-dialog.tsx]: Ok, we cannot just read the values to subscribe to them ?

for example:

```
const {
    register,
    handleSubmit,
    // Read the formState before render to subscribe the form state through the Proxy
    formState: { isDirty, isValid},
  } = useForm();
```

see: https://react-hook-form.com/docs/useform/formstate
Maybe i'm wrong, i'm new to FE & did not use a lot of react hook form but useMemo looks weird on a boolean check condition for me.

Comment (pr0m3th3usEx) [reply components/dialogs/gatekeeper-management-dialog.tsx]: Yeah actually, should be sufficient :) 
a4f559b2

**Review by MikaelVallenet — APPROVED** [review]
