### PR TITLE
feat(front): Add timezone on event details display + fix map not following marker when position changes

### LINKED ISSUE #285: feat: show the timezone in event render
When you create an event to another timezone, the startDate and endDate are not set according to the timezone 

I create an event in Seoul, Korea from the 25th March 2025 at 9 a.m to the 26th at 8 p.m (TZ: Asia/Seoul)

Image

When I am looking at the event from my browser in CET timezone:

Image

I should have displayed either have the same dates with the timezone precised (to avoid confusion) or the dates displayed relatively to my timezone: 
- `startDate`  would be 1 a.m (-8 from CET)  & `endDate` would be 12 a.m

On edit the timezone should use the timezone stored (currently displayed browser current timezone which is wrong):

Image

### LINKED ISSUE #286: bug: timezone is not properly parsed in edit-event page
extracted from #285 

thanks @pr0m3th3usEx 

I create an event in Seoul, Korea from the 25th March 2025 at 9 a.m to the 26th at 8 p.m (TZ: Asia/Seoul)

Image

On edit the timezone should use the timezone stored (currently displayed browser current timezone which is wrong):

Image

### PR DESCRIPTION
**Pull request by pr0m3th3usEx**
Fix #285
Fix #286 

- [X] Add timezone display on `EventInfo`
- [X] Use correct initial timezone when editing event (Missing correct handling `virtual` #286)
- [X] Fix Map no-movement on Marker position change

Screenshot 2025-03-20 at 20 00 02

### CODE REVIEW

File: app/hooks/use-location-timezone.ts [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+
+  useEffect(() => {
+    const determineTimezone = async () => {
+      switch (location.kind) {
+        case "custom":
+          return location.timeZone === ""
+            ? currentTimezone()
+            : location.timeZone;
+        case "virtual":
+          // ! Change to organizer timezone (#286)
```
Comment (MikaelVallenet) [inline app/hooks/use-location-timezone.ts:18]:
```suggestion
```

so it's not the case anymore, we want to use the tz of the user isn't ?

File: components/form/components/form-field-location.tsx [hunk 2]
```diff
@@ -57,7 +57,7 @@ export const useSearchField = (value: string) => {
 
 export const FormFieldLocation: React.FC<{
```
Comment (MikaelVallenet) [inline components/form/components/form-field-location.tsx:58]: newbie front question i guess but i don't get what is changed in this file, could you explain me in 2 or 3 sentences what is about ?

File: lib/location.ts [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+        lat: eventLocation?.address.value.lat,
+        lng: eventLocation?.address.value.lng,
+        size: eventLocation?.address.value.size,
+      };
+      break;
+    case "virtual":
+      return {
+        kind: "virtual",
+        location: eventLocation?.address.value.uri,
+        // ! TODO Add timeZone
```
Comment (n0izn0iz) [inline lib/location.ts:28]: like discussed, no need to have a timezone there

**Review by n0izn0iz — CHANGES_REQUESTED** [review]
