### PR TITLE
fix(front): Update Aspect-Ratio Video Markdown + Disable sentry report for specific errors

### LINKED ISSUE #526: bug: youtube video aspect ratio is weird
see: https://zenao-staging.vercel.app/event/26

### LINKED ISSUE #530: featreq: don't report `user is already participant for this event` errors in sentry
and in general do not report known errors that come from bad usage from user and are clearly explained in error toast

### LINKED ISSUE #531: featreq: make sure sentry reports are properly segregated
We should make sure different errors appears as different sentry reports

For example:

https://sentry.samourai.pro/organizations/sentry/issues/11/events/31ea5fc685a04c3287ef15e5332b9139/?environment=production&project=3&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&stream_index=0

`That email address is taken. Please try another.`

and

https://sentry.samourai.pro/organizations/sentry/issues/11/events/8d43107b08fe4bc5b614a04c8b47dcae/?environment=production&project=3&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&stream_index=0

`[unknown] user is already participant for this event`

are considered the same error, maybe because the title is `ConnectError`

### PR DESCRIPTION
**Pull request by pr0m3th3usEx**
fix #526
fix #530
fix #531

### CODE REVIEW

File: lib/get-query-client.ts [hunk 1]
```diff
@@ -30,6 +30,16 @@ function makeQueryClient() {
     mutationCache: new MutationCache({
       onError: (error) => {
         if (process.env.NEXT_PUBLIC_ENV ?? "development" !== "development") {
+          // Ignore specific errors
+          if (
+            error instanceof Error &&
+            (error.message === "Invalid password" ||
+              error.message ===
+                "[unknown] user is already participant for this event")
+          ) {
```
Comment (n0izn0iz) [inline lib/get-query-client.ts:39]: I think we shouldn't do the filtering for mutations in this generic file.
Consider removing the `mutationCache` customization and call `captureException` at callsites when we have an unexpected error.

Comment (pr0m3th3usEx) [reply lib/get-query-client.ts]: Gonna create an issue
