### PR TITLE
fix(front): event not found error handler

### LINKED ISSUE #368: bug(front): Display a not found page when event not found
Image

### PR DESCRIPTION
**Pull request by pr0m3th3usEx**
Fix #368

### CODE REVIEW

File: lib/queries/event.ts [hunk 1]
```diff
@@ -11,6 +11,7 @@ export const eventOptions = (id: string) =>
       const client = new GnoJSONRPCProvider(
         process.env.NEXT_PUBLIC_ZENAO_GNO_ENDPOINT || "",
       );
+      console.log("Running");
```
Comment (WaDadidou) [inline lib/queries/event.ts:14]: We should remove this console.log, or log something more relevant

**Review by WaDadidou — APPROVED** [review]
LGTM :)

File: lib/queries/event.ts (hunk 1 above)
Comment (pr0m3th3usEx) [reply lib/queries/event.ts]: @WaDadidou  Fixed

File: app/event/[id]/page.tsx [hunk 2]
```diff
@@ -25,7 +26,9 @@ export async function generateMetadata({ params }: Props): Promise<Metadata> {
   const id = (await params).id;
 
   const queryClient = getQueryClient();
-  const event = await queryClient.fetchQuery(eventOptions(id));
+  const event = await queryClient.fetchQuery(eventOptions(id)).catch((_) => {
+    notFound();
+  });
```
Comment (n0izn0iz) [inline app/event/[id]/page.tsx:31]: avoid mixing async/await will callback style (`.catch`) please

```suggestion
  let event
  try {
    event = await queryClient.fetchQuery(eventOptions(id))
  } catch {
    notFound()
  }
```

**Review by n0izn0iz — CHANGES_REQUESTED** [review]

**Review by n0izn0iz — CHANGES_REQUESTED** [review]

File: app/event/[id]/page.tsx (hunk 2 above)
Comment (n0izn0iz) [reply app/event/[id]/page.tsx:31]: also you could use an error boundary instead of try/catch

Comment (pr0m3th3usEx) [reply app/event/[id]/page.tsx]: Fixed

File: app/event/[id]/page.tsx [hunk 3]
```diff
@@ -41,10 +44,16 @@ export default async function EventPage({ params }: Props) {
...
 
-  const eventData = await queryClient.fetchQuery(eventOptions(p.id));
-  if (eventData) {
-    void queryClient.prefetchQuery(profileOptions(eventData.creator));
-  }
+  const eventData = await queryClient
+    .fetchQuery({
+      ...eventOptions(p.id),
+    })
+    .catch((err) => {
```
[the remark this answers is not in the document]
Comment (pr0m3th3usEx) [reply app/event/[id]/page.tsx]: Fixed

File: lib/queries/event.ts (hunk 1 above)
Comment (pr0m3th3usEx) [reply lib/queries/event.ts]: Can't use local error boundary yet: https://github.com/vercel/next.js/discussions/49925#discussioncomment-10445745

**Comment by n0izn0iz** [comment]
nice, thanks for adding the e2e test
